version: '3'

services:
  app:
    image: php:8.1.0-fpm
    container_name: crowdfunding-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: crowdfunding-db
    environment:
      MYSQL_DATABASE: crowdfunding
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_RANDOM_ROOT_PASSWORD:
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: crowdfunding-webserver
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - app

  composer:
    image: composer:latest
    container_name: crowdfunding-composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["install", "--ignore-platform-reqs"]

  artisan:
    image: php:8.1.0-fpm
    container_name: crowdfunding-artisan
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - db
